### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by 420binx03** [BeckettOBrien/BTManager#1]
When downloading from Cydia and the zebra manager I get a 404 error and fail to download tweak message. 
![3BB68D33-AB60-4FF6-A036-4FA4F1BB13A6](https://user-images.githubusercontent.com/71413141/93400802-e95b7500-f83d-11ea-9c8c-8347d597f30a.png)
 I cant post the picture of the zebra error cause I’m in the in-app browser. This looks like an amazing tweak I’d love to have please fix!

**Comment by BeckettOBrien** [comment]
That was an error with the repo, and they should have fixed it now. Feel free to contact me if you have any more problems

**Comment by 420binx03** [comment]
It still appears to not be working on cydia, but it worked on the zebra manager and the tweak is awesome, great work!

Thanks, Bryce

**Comment by BeckettOBrien** [comment]
The 404 Cydia error has now been fixed by Chariz
