### ISSUE TITLE
Changing default behaviour

### ISSUE THREAD

**Issue by dancheskus** [BeckettOBrien/BTManager#4]
After installing tweak, all devices are asking permission to connect by default. Even if toggle is disabled. So to disable it I should enable and disable toggle in each devices

**Comment by BeckettOBrien** [comment]
Ok, I'll give this a look when I get back from break so hopefully I can get this fixed in a week or so.

**Comment by BeckettOBrien** [comment]
@dancheskus I wasn't able to fully reproduce this issue, but I think I was able to fix it. Could you take a look and make sure it's all fixed?

[com.beckettobrien.btmanager+_1.1.2-2+debug_iphoneos-arm.deb](https://cdn.becketto.dev/com.beckettobrien.btmanager+_1.1.2-2+debug_iphoneos-arm.deb)

**Comment by dancheskus** [comment]
The strange thing is that I cannot't reproduce this issue also. I don't know what was changed. I even removed `btmanagerprefs.plist`. But I didn't saw issue again.

**Comment by BeckettOBrien** [comment]
Ok, I'm going to close this issue then, but if you ever run into this issue again feel free to reopen it.
